apiVersion: v1
data:
  prometheus.yml: |
    global:
      evaluation_interval: 15s
      scrape_interval: 5s
      scrape_timeout: 5s
    scrape_configs:
    - job_name: prometheus
      static_configs:
      - targets:
        - kafkadummyservice:8080
    - job_name: producer
      static_configs:
      - targets:
        - kafka-producer-service:5000
    - job_name: consumer
      static_configs:
      - targets:
        - kafka-consumer-service:5000
kind: ConfigMap
metadata:
  name: dummy-prom-prometheus-server
  annotations:
    meta.helm.sh/release-name: dummy-prom
    meta.helm.sh/release-namespace: default
  labels:
    app: prometheus
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-13.6.0
    component: server
    heritage: Helm
    release: dummy-prom
