---

packages: "['tc', 'kubelet-1.20.2-0.x86_64', 'kubeadm-1.20.2-0.x86_64', 'kubectl-1.20.2-0.x86_64', 'containerd.io-1.4.3-3.1.el8.x86_64']"

yum_repos:
 - Docker.repo
 - Kubernetes.repo

kernel_modules:
 - br_netfilter

sysctl_records:
 - net.ipv4.ip_forward
 - net.bridge.bridge-nf-call-iptables
 - net.bridge.bridge-nf-call-ip6tables 

rc_local_records:
 - "swapoff -a"
